options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gsp48wdcrbp/springboot-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gsp48wdcrbp/springboot-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - springboot-app
      - --image
      - gcr.io/gsp48wdcrbp/springboot-app
      - --platform
      - managed
      - --region
      - asia-southeast1
      - --allow-unauthenticated
      - --memory
      - 512Mi
      - "--set-env-vars=SPRING_DATASOURCE_URL=jdbc:mysql://interchange.proxy.rlwy.net:11501/wdcrbp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC,SPRING_DATASOURCE_USERNAME=root,SPRING_DATASOURCE_PASSWORD=tZUlYlcvdvjUxXGvFFLRxLWZOZvUgrgS,SPRING_JPA_HIBERNATE_DDL_AUTO=none,SPRING_MAIL_HOST=smtp.gmail.com,SPRING_MAIL_PORT=587,SPRING_MAIL_USERNAME=namndpse171442@fpt.edu.vn,SPRING_MAIL_PASSWORD=mqmk okcr vxaj kxcy,APP_JWT_SECRET=186e4b79e23b663a99f7824f3c48066c517258bbaa8237d45fec6b31e0cca51b,APP_JWT_ACCESS_EXPIRATION_MILLISECONDS=86400000,APP_JWT_REFRESH_EXPIRATION_MILLISECONDS=604800000,VNPAY_TMNCODE=74B7NM0Y,VNPAY_VERSION=2.1.0,VNPAY_COMMAND=pay,VNPAY_SECRETKEY=QHRX1ELPYEDJQ2OE8WHORG63N9QZ8ZGQ"
