options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gsp48wdcrbp/springboot-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gsp48wdcrbp/springboot-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - springboot-app
      - --image
      - gcr.io/gsp48wdcrbp/springboot-app
      - --platform
      - managed
      - --region
      - asia-southeast1
      - --allow-unauthenticated
      - --memory
      - 512Mi
